name: Develop Deployment
on:
  workflow_call:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: build-test
        uses: ./.github/actions/build-and-test

  develop:
    needs: build-and-test
    name: Develop Deployment
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: build-test
        uses: ./.github/actions/push-branch
        with:
          branch-name: development
          github-secret: ${{ secrets.GITHUB_TOKEN }}
