on:
  push:
    branches:
      - main
name: Release Please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
      - uses: actions/checkout@v2
      - name: Build & Test
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/build-and-test
      - name: Deploy Development
        if: ${{ steps.release.outputs.release_created }}
        uses: ./.github/actions/push-branch
        with:
          branch-name: development

